#include<stdio.h>
#include<unistd.h>
#include<stdlib.h>

/**
 * WHEN YOU RUN THIS PROGRAM NORMALLY IT WILL PRINT:
 * Hello, World
 * NAMASTE
 *
 * BUT WHEN YOU RUN THIS PROGRAM AND REDIRECT OUTPUT TO A FILE, IT WILL PRINT:
 * NAMASTE
 * Hello, World
 * Hello, World
 */

int main() {
    printf("Hello, World \n");
    write(STDOUT_FILENO, "NAMASTE\n", 8);

    if(fork() == -1) {
        perror("fork");
        exit(EXIT_FAILURE);
    }

    exit(EXIT_SUCCESS);
}

/**
 * THE REASON WHY SECOND APPROACH WRITES HELLO WORLD TWICE IS THAT
 * STDIO BUFFERS ARE MANTAINED ON USER SPACE HENCE THIS MEMORY IS DUPLICATED BY CHILD PROCESS
 * WHEN STANDARD OUTPUT IS DIRECTED TO TERMINAL IT IS LINE BUFFERED BY DEFAULT, WITH THE RESULT
 * THAT NEW LINE TERMINATED STRING WRITTEN BY PRINTF APPEARS IMMEDIATELY
 *
 * HOWEVER WHEN STDOUT IS REDIRECTED TO FILE IT IS BLOCK BUFFERED BY DEFAULT, SO IN OUR
 * PROGRAM THE STRING WRITTEN BY PRINTF IS STILL IN THE PARENT STDIO BUFFER AT THE TIME OF FORK
 * AND THIS STRING IS DUPLICATED TO THE CHILD WHEN LATER CHILD CALL EXIT THEY BOTH FLUSH THEIR
 * COPIES OF THE STDIO BUFFERS RESULTING IN DUPLICATE OUTPUT
 */

 /**
  * SOLUTION TO THIS PROBLEM IS TO USE FFLUSH, SETVBUF OR SETBUF TO FLUSH THE BUFFER
  * WE COULD ALSO CALL _EXIT INSTEAD OF EXIT TO AVOID FLUSHING STDIO BUFFERS, HENCE ONLY ONE EXIT FLUSHES THE BUFFER
  */
