#include<stdio.h>
#include<stdlib.h>
#include<sys/wait.h>

/**
 * WAIT HAS FOLLOWING LIMITATIONS:
 * IT IS NOT POSSIBLE TO WAIT FOR THE SPECIFIC CHILD PROCESS TO TERMINATE
 * WE CAN ONLY WAIT FOR THE NEXT CHILD PROCESS TO TERMINATE
 * IF NO CHILD HAS TERMINATED WAIT ALWAYS BLOCKS, SOMETIMES
 * WE MAY WANT TO PEFORM NON BLOCKING IO IF NO CHILD HAS TERMINATED
 * USING WAIT WE CAN ONLY FIND NUMBER OF CHILDREN TERMINATED
 * BUT NOT POSSIBLE TO NOTIFY WHEN A CHILD TERMINATES BY A SIGNAL LIKE SIGSTOP OR SIGCONT
 */

 /**
  *    SYNTAX
  * waitpid(pid_t pid, int *status, int options);
  * OPTIONS IS THE BITMASK OF FOLLOWING FLAGS
  * WUNTRACED: NOTIFY WHEN CHILD STOPS DUE TO SIGNAL
  * WCONTINUED: NOTIFY WHEN CHILD CONTINUES AFTER STOPPED
  * WNOHANG: RETURN IMMEDIATELY IF NO CHILD HAS TERMINATED
  */

int main() {


    return 0;
}
